// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmkoiaglbvkxszbipzul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJta29pYWdsYnZreHN6YmlwenVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzgyMTEsImV4cCI6MjA2Mjg1NDIxMX0.Ym_fyEFWZYRKmFL0fWkc4uNxwyF3oiXESARQvZ9B2WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);